### ISSUE TITLE
Review all the links

### ISSUE THREAD

**Issue by nivu** [nivu/ai_all_resources#12]
This repo is 4yrs old. A few links are not been working recently. Review all the links and restructure contents under topics.

**Comment by Dhanush-Manick** [comment]
@nivu  I can work on this.

**Comment by nivu** [comment]
> @nivu I can work on this.

Hi @Dhanush-Manick hope you have started verifying the links.

**Comment by Dhanush-Manick** [comment]
Verified all the links sir

**Comment by nivu** [comment]
> Verified all the links sir

Awesome @Dhanush-Manick
